name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_ENV: test
  BACKEND_PORT: 3001
  FRONTEND_PORT: 3000
  POSTGRES_PORT: 5432
  JWT_EXPIRE: 1h
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NODE_ENV: test
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    # env:
    #   DATABASE_URL: ${{ secrets.DATABASE_URL }}
    #   NODE_ENV: test
    #   JWT_SECRET: ${{ secrets.JWT_SECRET }}
    #   JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
    #   PORT: 3001
      # JWT_EXPIRE: 1h

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        # cache: 'npm'

    - name: Install backend dependencies
      working-directory: ./blog-platform-be
      run: npm ci

    - name: Run backend ESLint
      working-directory: ./blog-platform-be
      run: npm run lint

    - name: Run backend tests
      working-directory: ./blog-platform-be
      run: npm run test


  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install frontend dependencies
      working-directory: ./blog-platform-fe
      run: npm install

    - name: Run frontend ESLint
      working-directory: ./blog-platform-fe
      run: npm run lint

    - name: Build frontend
      working-directory: ./blog-platform-fe
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: http://localhost:3001
        NEXT_PUBLIC_BASE_URL: http://localhost:3000